language: c
matrix:
  include:
  - os: osx
    env: PLAT=osx
         PIP=pip3
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
         PLAT=manylinux1_x86_64
         PIP=pip
    python:
      - "3.6" 
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
         PRE_CMD=linux32
         PLAT=manylinux1_i686
         PIP=pip
    python:
      - "3.6" 
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
         PLAT=manylinux2010_x86_64
         PIP=pip
    python:
      - "3.6" 

before_install:
  - if [[ "$PLAT" == "osx" ]]; then rvm get stable || true; fi
  - if [[ "$PLAT" == "osx" ]]; then brew update || true; fi
  - if [[ "$PLAT" == "osx" ]]; then brew install python3 || brew upgrade python3 || true; fi
  - if [[ "$PLAT" == "osx" ]]; then export PATH=/Users/travis/Library/Python/3.7/bin:$PATH; fi
  - $PIP install --user wheel twine
  - which twine
  - twine --version

install:
  - if [[ "$PLAT" != "osx" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ "$PLAT" == "osx" ]]; then python3 setup.py bdist_wheel; fi
  - if [[ "$PLAT" == "osx" ]]; then ls dist/; fi
  - if [[ "$PLAT" != "osx" ]]; then docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh; fi
  - if [[ "$PLAT" != "osx" ]]; then ls wheelhouse/; fi

env:
  global:
    - TWINE_USERNAME=jeff.daily
    # Note: TWINE_PASSWORD is set in Travis settings

deploy:
  provider: script
  script:
    - if [[ "$PLAT" == "osx" ]]; then twine upload dist/parasail*.whl
    - if [[ "$PLAT" != "osx" ]]; then twine upload wheelhouse/parasail*.whl   
  skip_cleanup: true
  on:
    tags: true
