language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.5
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python37/python.exe /c/Python37/python3.exe

env:
  global:
    - CIBW_BUILD="cp37-*"
    - CIBW_TEST_COMMAND="python3 -m unittest discover {project}/tests"
    - TWINE_USERNAME=__token__

install:
  - python3 -m pip install cibuildwheel==1.6.4 wheel
  - python3 -m pip install --upgrade --upgrade-strategy eager twine
  - wget -O parasail-master.zip https://github.com/jeffdaily/parasail/archive/master.zip

script:
  - python3 -m cibuildwheel --output-dir wheelhouse
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]];  then python3 setup.py sdist -d wheelhouse; fi

after_success:
  - if [[ $TRAVIS_TAG ]]; then python3 -m pip install --upgrade --upgrade-strategy eager twine ; fi
  - if [[ $TRAVIS_TAG ]]; then python3 -m twine upload wheelhouse/* ; fi
